# Generated by Django 4.0.2 on 2022-02-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('qualification', models.CharField(choices=[('High School', 'High School'), ('Pre University (XII)', 'Pre University (XII)'), ('Diploma', 'Diploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctoral Degree', 'Doctoral Degree')], max_length=30, null=True, verbose_name='Highest Qualification')),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
